### ISSUE TITLE
Run Tensorflow model on GPU

### ISSUE THREAD

**Issue by andreapairon** [kserve/modelmesh-serving#105]
I was trying to run the `example-tensorflow-mnist` on GPU.
To achieve this, I edited the `ServingRuntime`  object adding `nvidia.com/gpu: 1` to the `spec.containers.resources.limits` and  `spec.containers.resources.requests `sections of the `tritonserver` container and the needed `tolerations`.
Once done that, I noticed that the `example-tensorflow-mnist` predictor always failed to be loaded.

This is the error I'm getting from the `Predictor`:
`UNAVAILABLE: Failed to load Model due to Triton runtime error: rpc error: code = Unavailable desc = error reading from server: EOF`

Before setting the `nvidia.com/gpu: 1` I was able to run an inference on `example-tensorflow-mnist`.

My goal is to load with success the model and then run an inference using the GPU.

Thanks in advance.

**Comment by njhill** [comment]
@andreapairon from what you described it sounds like Triton may not be running properly in the GPU case, and possibly restarted. Could you check whether the `triton` container in any of the pods restarted, and also look at the logs from that container for clues?

**Comment by andreapairon** [comment]
@njhill unfortunately, at the moment, I'm not able to assign any predictor to any runtime due to the following error from the `modelmesh-controller`:

`{"level":"info","ts":1642066059.726149,"logger":"controllers.ServingRuntime","msg":"No runtime found to support predictor","name":"example-mnist-predictor","source":"Predictor"}`

I tried to uninstall and reinstall ModelMesh a couple of times and to follow the quickstart installation guide, but the above error comes up every time :(

All the needed pods and serving runtimes are deployed:
![image](https://user-images.githubusercontent.com/16152588/149305716-1240471e-a396-4ee7-a9e4-a82ce3ba046a.png)
![image](https://user-images.githubusercontent.com/16152588/149305820-89f19d29-8dd6-484a-ae0c-5b93f14a07c6.png)

Seems strange because yesterday always worked fine.

Any ideas?

**Comment by njhill** [comment]
@andreapairon changing the pod/container config for GPU should not have affected the logic to match predictors with runtimes. Really the next step in diagnosis is inspecting the triton runtime Deployment/Pods - even before checking the logs just verifying that the pod and containers are running and in ready state, and not restarting unexpectedly. And even if you can't provide the raw logs, maybe you can inspect them yourself for clues. It should be straightforward to get them using `kubectl logs -c triton <podname>` (if the container has restarted also try with `--previous=true` arg).

**Comment by andreapairon** [comment]
Log update:

the `triton` logs (before the restart) seems really ok:

![image](https://user-images.githubusercontent.com/16152588/149804665-7ff221ba-b114-4ee3-99f2-ea9f40394f40.png)

the `triton-adapter` downloads the needed object (.**pbtxt** and .**pt** files) but then crashes due to an error: 
`"error": "rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp [::1]:8001: connect: connection refused\""`

![image](https://user-images.githubusercontent.com/16152588/149805054-5cac43f0-3a6c-4fee-a633-47269ff1edd4.png)

**Comment by njhill** [comment]
@andreapairon I'm still not completely sure what's going on but my guess based on all the evidence above is that this is the significant part:
> if I start with the GPU config (without Predictors created earlier) the triton pods are not created.

My guess is that when you got Triton to start loading the pod, it was actually the CPU configured version of it, and the loading failed because the pods were torn down due to the GPU reconfiguration. The errors shown above shouldn't have caused the adapter container to crash - probably it was killed but slightly _after_ the triton container was killed, latter could explain the above observed errors (and you seem to imply that saying "before the restart").

To help get to the bottom of this, could you check the state of the triton _Deployment_ assuming it exists but has no running pods. If you `kubectl describe` it there should be some clues in the status/events at the bottom - you may need to follow the referenced replicasets and describe those too to see relevant messages.

And/or it would be useful to get the log of the modelmesh-serving _controller_ (different deployment/pod) while all of this is going on. This is what translates the ServingRuntime to a Deployment and so may contain some relevant errors.

**Comment by ckadner** [comment]
This issue has been stale for two years and much of the code has changed since. Feel free to reopen if you can still reproduce this issue in the latest version of [ModelMesh-Serving v0.11.2](https://github.com/kserve/modelmesh-serving/releases/tag/v0.11.2).
