### ISSUE TITLE
kserve python SDK for modelmesh serving predictor API v1alpha1

### ISSUE THREAD

**Issue by portkey2112** [kserve/modelmesh-serving#180]
## Overview

I want to create predictor CRD for modelmesh serving using Python SDK. The APIs for predictor is v1alpha1. But it is not available in kserve Python SDK. In https://kserve.github.io/website/sdk_docs/sdk_doc/, v1beta1 functions are available. Using v1beta1, we can create inference service and not predictor alone. Is this correct? And to create isvc, I need to install kserve along with modelmesh which is additional installation for just isvc. 

(I have created isvc for tensorflow model type predictor for modelmesh serving using V1beta1TFServingSpec. I am not sure if this can be continued going forward due to api mismatch/ extra kserve installation for isvc CRD )

Please help on how to go forward.

### Questions

- How can I create modelmesh predictor CRD using Python SDK for v1alpha1 API ? 

### Versions

- kserve version: release 0.8

### Reference

- https://github.com/kserve/kserve/releases (modelmesh is v1alpha1)
- https://kserve.github.io/website/sdk_docs/sdk_doc/ (This doc does not introduce v1alpha1 APIs)

**Comment by pvaneck** [comment]
The KServe SDK should work for deploying InferenceServices on ModelMesh Serving. I'm in the the process of updating the docs to have the `InferenceService` CRD be the primary interface for interacting with ModelMesh instead of the `Predictor` CRD. 

Some docs for ISVC: https://github.com/kserve/modelmesh-serving/blob/main/docs/inferenceservice.md but this still needs to be updated to use the new predictor modelspec as shown [here](https://github.com/kserve/modelmesh-serving/blob/main/fvt/testdata/isvcs/new-format-mm.yaml).

You do not necessarily need kserve and its dependencies (knative/istio) installed. As long as the InferenceService [CRD](https://raw.githubusercontent.com/kserve/kserve/master/config/crd/serving.kserve.io_inferenceservices.yaml) is installed, then you should be able to deploy onto ModelMesh using the KServe SDK.

**Comment by portkey2112** [comment]
Thanks @pvaneck. The kserve SDK has worked for modelmesh serving as well. I was concerned about the additional installation of kserve. But now, will go ahead with inference service CRD alone. Thank you for the immediate response! This helped.
