### ISSUE TITLE
Resource requirement for ModelMesh sidecar and model puller

### ISSUE THREAD

**Issue by yuzisun** [kserve/modelmesh-serving#182]
Currently the default modelmesh sidecar container by default requires [3 CPUs](https://github.com/kserve/modelmesh-serving/blob/main/config/default/config-defaults.yaml#L25) and model puller requires [2 CPUs](https://github.com/kserve/modelmesh-serving/blob/main/config/default/config-defaults.yaml#L49), just wondering if there is any rationales with these numbers as this does add a big overhead to each modelmesh replica especially with the cluster turned on with resource quota running large scale modelmesh deployments.

Alternatively we can also support overriding these numbers on serving runtimes so user can tune the resource requirement themself.

**Comment by njhill** [comment]
@yuzisun those numbers are the `limits` values, which in general are worth setting quite high for CPU so that spare cycles can be used if available on the node. The actual allocation/requirement is indicated by the `requests` values which are much lower.

When setting resource quotas I'd recommend having the `limits` quota be many times higher than the `requests` quota (latter should reflect the actual capacity of the nodes).

Even so, these defaults _are_ overridable - just set the corresponding attributes in the global ["user" ConfigMap](https://github.com/kserve/modelmesh-serving/tree/main/docs/configuration) yaml (they aren't documented in the table on that page since we didn't expect that they would generally need to be changed). They can't be overridden per `ServingRuntime` but hopefully that's not a big deal.

**Comment by yuzisun** [comment]
Our namespace quota limits are set according to each tenant's budget, if we set many times higher they will need to budget a lot more.

**Comment by njhill** [comment]
@yuzisun so how do you set quota CPU `limits` values set in relation to the `request` values? Having a high limit doesn't guarantee/reserve that resource, everyone's CPU limit could even be set to `unlimited`. It's useful for containers to be able to temporarily "burst" beyond their allocation when there are spare cycles on the node (especially true for the puller which is idle most of the time but might require nontrivial cpu intermittently).

In any case, if this is a problem you can reduce the `limits` values to be closer to the `request` values for those containers in the ConfigMap as mentioned.
