### ISSUE TITLE
Manager config mounted wrongly

### ISSUE THREAD

**Issue by adrwong-lora** [kserve/modelmesh-serving#205]
**To Reproduce**

1. install modelmesh in microk8s from scratch without --quickstart
2. use `kubectl exec` to get in the manager pod
3. cd /etc/model-serving
4. the config-defaults.yaml here is a directory, which contains a real config-defaults.yaml
5. the mount setting can be found in https://github.com/kserve/modelmesh-serving/blob/main/config/manager/manager.yaml

**Expected behavior**

the config-defaults.yaml should not be a directory itself

**Comment by ckadner** [comment]
Interesting. I plan to take a look at this in the next couple of days.

**Comment by njhill** [comment]
@adrwong-lora while not very tidy, I don't think this is actually a bug since I'm pretty sure the controller process is looking for the file where it's currently mounted. There would be no harm in simplifying though to remove the intermediate `config-defaults.yaml` directory.

Did you actually run into any problems functionally or this was just something you noticed that looked odd?

**Comment by adrwong-lora** [comment]
It works fine, just a bit confused when I tried to look for the config-defaults.yaml it's actually reading in the pods.
