### ISSUE TITLE
horizontal Pod autoscaler available for the serving runtime

### ISSUE THREAD

**Issue by Agarwal-Saurabh** [kserve/modelmesh-serving#225]
I was looking on serving runtime but there is only option for replica and there is no horizontal Pod autoscaler available for the serving runtime.

is there a way to setup HPA for pods with serving runtimes instead setting replicas hardcoded @njhill

**Comment by njhill** [comment]
@Agarwal-Saurabh there isn't currently a way to do this. Basic HPA might not be the best fit because it assumes homogeneous deployments, whereas with modelmesh there can be an intentional imbalance in resource usage depending on how models are distributed amongst the pods and their volume of usage.

But it would be good look into this further and provide suitable way to integrate with HPA and/or incorporate some similar pod-level scaling in the modelmesh-serving controller.

There's some additional discussion in this issue: https://github.com/kserve/modelmesh/issues/46.
