### ISSUE TITLE
{"code":3,"message":"json: cannot unmarshal string into Go struct field RESTRequest.inputs of type predictv2.InferParameter"}

### ISSUE THREAD

**Issue by MLHafizur** [kserve/modelmesh-serving#259]
Trying to make prediction with string data load:

```
sentences = [base64.b64encode(x.encode('utf-8')).decode('utf-8') for x in sentences]

payload = InferenceRequest(
    inputs=[
        StringCodec.encode_input('sentences', sentences, use_bytes=False),
    ]
)
response = requests.post("http://localhost:8008/v2/models/muc-en-aa-predictor/infer", json=payload.dict())
```
getting error:
`{"code":3,"message":"json: cannot unmarshal string into Go struct field RESTRequest.inputs of type predictv2.InferParameter"}`

**`payload.dict() :::`**
```
{
  'id': None,
  'parameters': None,
  'inputs': [
    {
      'name': 'sentences',
      'shape': [
        3
      ],
      'datatype': 'BYTES',
      'parameters': {
        'content_type': 'str',
        'headers': None
      },
      'data': [
        'QSBTaW5nYXBvcmUgR292ZXJubW5nYXBvcmU=',
        'YWRvYmUgaW5jIGFkZCBySBsaXR0bGVzaXMgcmVhZCBkaXNjbGFpbWVy',
        'Y29sbGVlbiBwb3VsaWhZCBkaXNjbGFpbWVy'
      ]
    }
  ],
  'outputs': None
}
```
What is the issue here? How to overcome this?

**Comment by njhill** [comment]
@MLHafizur parameter handling is another current gap in the implementation, see https://github.com/kserve/rest-proxy/issues/13.  This should be straightforward to fix, I will aim to do it soon if no one else does. However even with that fix I'm not sure your request will work due to the current lack of support for string-encoded `BYTES` type tensors (as discussed in your other issue https://github.com/kserve/modelmesh-serving/issues/255).

**Comment by MLHafizur** [comment]
@njhill can you please tell me the alternative supported solution for string data?

**Comment by njhill** [comment]
@MLHafizur I'm not sure there's a way to do it currently using via REST, the workaround would be to use gRPC directly. I'll aim to add the string support soon.
