### ISSUE TITLE
Create isolation between serving runtimes

### ISSUE THREAD

**Issue by xvnyv** [kserve/modelmesh-serving#283]
**Is your feature request related to a problem? If so, please describe.**

In my team’s use case, we are currently using the [KServe V2 Inference Protocol REST API](https://kserve.github.io/website/modelserving/inference_api/#inference-request-examples) for sending inference requests. On top of this protocol, we also make use of multiple virtual services to direct traffic to the `modelmesh-serving` service such that each serving runtime should be mapped to one virtual service.

Our use case does not allow us to match the `/v2/models/<model-id>/infer` in our virtual service, and this creates a problem for us because requests sent to the virtual service for serving runtime X can end up reaching models loaded in serving runtime Y due to the fact that:
* All serving runtimes share the same `modelmesh-serving` service
* Users can set the model id to any existing inference service name in the request path

**Describe your proposed solution**

Since this is an unwanted behaviour for my team, we have 2 possible solutions for solving this.
1. Support `mm-vmodel-id` header in the REST API and allow it to take precedence over the model id specified in the V2 inference path
2. Create a dedicated service per serving runtime instead of having all serving runtimes share the same service

**Describe alternatives you have considered**

**Additional context**

**Comment by lizzzcai** [comment]
Hi @njhill, can you help to check this issue? @xvnyv is my colleague and we are gathering the issues we faced during the ModelMesh integration and feedback to the community, and see if there are any solutions or proposals for them. 

I think the quick solution for this it to have the option to get model_id from `mm-vmodel-id` header only (so we can inject the `mm-vmodel-id` on the gateway level). The current [logic](https://github.com/kserve/modelmesh/blob/main/src/main/java/com/ibm/watson/modelmesh/ModelMeshApi.java#L659-L673) seems that it will get from message first then fall back to headers. Do you see any issues here? (I have tested it and it is functionally working)

A better long-term solution is to have service per servingRuntime (in standard kserve flow, the service is per InferenceSerivce and we want to keep a `similar experience` and isolation) so that we have better isolation here.

Can you provide your opinion here, thanks.

**Comment by njhill** [comment]
@lizzzcai @xvnyv sorry for the delay responding to this. I was having trouble really understanding what you're trying to do.

A core idea of model-mesh is to abstract the details of where a model is running so that you can just call it by name and it will be routed accordingly. So I don't really understand the partitioning by serving runtime.

It sounds like you're maybe looking for multiple independent/disjoint logical instances of model-mesh within a given namespace (possibly still managed by the same controller), is that accurate? These would then have their own Service and Deployment(s) and may or may not use the same ServingRuntimes. This would make sense to me (and is actually how we use model-mesh in a non-KServe context... just multiple independent Service+Deployments within the same Kube namespace). In this case they have separate registries within etcd. But it may complicate things a fair amount to implement.

Adding a mode to the REST proxy where it gets the model id from a header rather than the path sounds ok to me, though it sill seems like a fairly niche/specific use case (I'm probably still not understanding completely).

**Comment by xvnyv** [comment]
Hi @njhill, thanks for the reply and apologies for the late response.

I believe your interpretation of what we are looking for is accurate. Perhaps the attached diagram can confirm whether we have the same idea in mind.

The rationale behind coming up with such a design would be to provide network isolation between different serving runtimes so that inference requests for models loaded on Runtime X will not go through the mesh of Runtime Y. Does this make sense?

![Architecture with isolated serving runtime](https://user-images.githubusercontent.com/48668369/224897551-e47f935e-4313-4599-8cc5-2154c21cebb6.png)

This feature is not something that we urgently require, but it would be helpful to us if this would be supported in the future. What do you think about supporting such a feature?

cc @lizzzcai

**Comment by ckadner** [comment]
@lizzzcai -- Did you end up finding a different solution? If this is this still a feature you are looking for, could you draft a PR with the changes you described?

I assume you meant this code block?
https://github.com/kserve/modelmesh/blob/v0.9.0/src/main/java/com/ibm/watson/modelmesh/ModelMeshApi.java#L659-L673

```Java
                        // First try to get id from the message
                        String modelId = ProtoSplicer.extractId(message, rpcConfig.getIdExtractionPath());
                        if (modelId != null) {
                            modelIds = Collections.singleton(modelId);
                            isVModel = rpcConfig.isvModelId();
                        } else {
                            // If target field is not set, fall back to looking for headers
                            ModelIds mids = getModelIdsFromHeaders(headers);
                            if (mids.errorStatus != null) {
                                call.close(mids.errorStatus, emptyMeta());
                                canInvoke = false;
                            }
                            modelIds = mids.modelIds;
                            isVModel = mids.isVmodel;
                        }
```


Instead of this one:
https://github.com/kserve/modelmesh/blob/main/src/main/java/com/ibm/watson/modelmesh/ModelMeshApi.java#L659-L673

```Java
            // When not doing id extraction, try to resolve model ids from headers
            // so that we can fail-fast if necessary.
            mids = getModelIdsFromHeaders(headers);
            if (mids.errorStatus != null) {
                call.close(mids.errorStatus, emptyMeta());
                return (Listener<ByteBuf>) EMPTY_LISTENER;
            }
        } else {
            mids = ModelIds.DEFAULT; // not yet determined
        }

        call.request(2); // request 2 to force failure if streaming method

        return new Listener<>() {
            ByteBuf reqMessage;
```

The line numbers may have shifted due to code additions since Nov 2022.
