### ISSUE TITLE
Help: Models not unloading dynamically as per LRU

### ISSUE THREAD

**Issue by dumbPy** [kserve/modelmesh-serving#312]
**Is your feature request related to a problem? If so, please describe.**

Sorry, I have an Issue, not a feature request but also not a bug, so using feature request template.

***Problem:***
I tried modelmesh a couple of months back and it use to unload the least recently used model after some timeout once the GPU memory went above 50%.

I reinstalled the setup again recently and it isn't doing that anymore for me. I had 7 models loaded for 90% of memory for 2 days, unused, and yet it didn't unload the models.

I guess there might be some config for the LRU behaviour that I am missing.

Thanks a lot in advance.

**Describe alternatives you have considered**
Tried going through the default config and couldn't find anything related to LRU or timeout for dynamic unloading of models.

**Comment by njhill** [comment]
@dumbPy eviction isn't time-based, models will only be evicted if the space is needed for copies of other models. Unfortunately the way that the spaced consumed by models is determined is fairly crude, the runtime reports a size when the model is loaded and this is subtracted from an overall capacity. So it has to take into account extra model-specific space needed during inferencing.

The accounting is also one-dimensional, I was deliberately using the vague term "space"  since it could refer to either CPU or GPU memory.

**Comment by dumbPy** [comment]
triton supports model warmup as part of model loading. that should take care of space requirements for inferencing.
I am already using that though.  
Is there any way for a novice to debug why the models were not unloaded even after being unused and new models needing memory ? Any specific logs I can look at for this ?

**Comment by njhill** [comment]
@dumbPy again if new models need memory then they should cause existing models to be evicted if there isn't sufficient. But there is no inactivity-based eviction otherwise.

You may need to adjust some of the parameters to increase the fixed mem overhead and/or model size multiplier, this answer might help: https://github.com/kserve/modelmesh/issues/82#issuecomment-1435434649
