### ISSUE TITLE
Enable REST support

### ISSUE THREAD

**Issue by pvaneck** [kserve/modelmesh-serving#6]
Currently only gRPC inference requests are supported with ModelMesh. However, there is a need for REST support in order to smoothen the user experience of interacting with ModelMesh models.

Currently, the idea is to have a transcoder container/service that will transcode the REST v2 protocol JSON into the gRPC format ModelMesh expects (and vice versa). The transcoding mappings will have to be explored, and performance will need to be kept in mind.

**Comment by pvaneck** [comment]
FYI, made a simple prototype: https://github.com/pvaneck/modelmesh-proxy.

This leverages the grpc-gateway project, which there may have been some reservations about, but it seems to work fine for handling rest inference requests.

**Comment by njhill** [comment]
Thanks @pvaneck, this is great. Having looked at grpc-gateway again I realize that it probably could work if we have a custom marshaller. What you have so far though doesn't implement the KFSv2 REST API because it does not map directly to the protobuf one.

i.e. the example in your readme
```
{ "inputs": [{ "name": "predict", "shape": [1, 64], "datatype": "FP32", "contents": { "fp32_contents": [0.0, 0.0, 1.0, ...
```
is not a valid KFSv2 inference request json payload. It would instead be something like
```
{ "inputs": [{ "name": "predict", "shape": [1, 64], "datatype": "FP32", "data": [0.0, 0.0, 1.0, ...
```
See https://github.com/kubeflow/kfserving/blob/master/docs/predict-api/v2/required_api.md

**Comment by pvaneck** [comment]
@njhill Yea, thanks for pointing that out. My latest iteration does add some custom marshaling logic to enable conformity with the REST v2 spec.  Probably need to revisit the the data array type coercion logic, but just wanted to get it working for now. 

As mentioned in a call last week, right now this transcoder is a separate go program in a container that has its own Deployment and a corresponding Service. I remember you having some thoughts for better integration with modelmesh-serving. Can you expound on what you had in mind?

**Comment by njhill** [comment]
Thanks @pvaneck.

> Can you expound on what you had in mind?

Ultimately, it would be good to generalize model-mesh to proxy http/h2 rather than just gRPC and to integrate any data plane transcoding logic into the same routing process. But in the meantime, my thinking was to include your container in the existing runtime deployment pods so that calls to the existing Service will hit them and each one forwards directly to its colocated model-mesh container. This would be pretty straightforward to arrange, and it would also be pretty easy to make this intra-Pod hop via a unix domain socket rather than going through the whole network stack which should help to minimize the performance overhead.

The controller wouldn't necessarily _always_ include/configure the transcoder, it could be done based on some global config parameter, and maybe a per-ServingRuntime property. And TBD exactly how to arrange the ports that are exposed via the service... maybe model-mesh can still accept "direct" gRPC requests on one port while the transcoder listens for HTTP requests on another.

**Comment by pvaneck** [comment]
@njhill Thanks for the explanation. That makes sense. I will try this out with the unix domain socket approach.
