### ISSUE TITLE
Add GCS storage provider to pullman

### ISSUE THREAD

**Issue by pvaneck** [kserve/modelmesh-serving#79]
The ModelMesh Runtime Adapter has been refactored to leverage a go-library named `pullman` . Currently it supports http and s3 based on the storage providers listed [here](https://github.com/kserve/modelmesh-runtime-adapter/tree/main/pullman/storageproviders). Since many KServe users use Google Cloud Storage, let's aim to add pullman support for GCS. 

For reference:

- GCS Go package: https://pkg.go.dev/cloud.google.com/go/storage
- KServe MMS Agent GCS puller logic: https://github.com/kserve/kserve/blob/master/pkg/agent/storage/gcs.go

**Comment by pvaneck** [comment]
FYI @tjohnson31415 . I'll work on this, but let me know if there are any gotchas or things to be wary of. I'll model the implementation off of the s3 storage provider.

**Comment by tjohnson31415** [comment]
It should be straightforward I think. Please raise any questions or suggestions you have as you are working through it.

One gotcha/note: I found out recently that my caching implementation doesn't work as intended. I used Golang's [`maphash.Hash`](https://pkg.go.dev/hash/maphash) to generate the cache keys, but it uses seeded RNG when it generates the hash. I didn't set the seed, so there is never a cache hit in my use of it (oops!). So that will need to be fixed...
