### ISSUE TITLE
ClusterServingRuntime support

### ISSUE THREAD

**Issue by pvaneck** [kserve/modelmesh-serving#81]
KServe supports cluster-scoped ServingRuntimes called `ClusterServingRuntimes`. These act as the built-in or default serving runtimes accessible to any user/namespace in the cluster. Currently ModelMesh-Serving only considers the the namespace-scoped `ServingRunimes`. Let's think about how ModelMesh-Serving can handle these cluster-level resources.

**Comment by njhill** [comment]
Summary of design discussion with @chinhuang007:
- A `ServingRuntime` in a given namespace will "hide" a `ClusterServingRuntime` with the same name for any inference services in that namespace
- Deployments derived from `ClsuterServingRuntime`s won't have an owner set, otherwise the `ServingRuntime` will be set as the owner as it is now
- When installing in cluster scope mode (default), the built-in runtimes will be created as `ClusterServingRuntime`s, otherwise they will be created as regular `ServingRuntime`s in the target namespace

Code changes required:
- Have the SR reconciler also watch CSRs, with a handler function that maps CSR events to multiple SR requests, one per "modelmesh-enabled" namespace
- In the Reconcile function, always `Get` the SR as we do now. If it is not found, attempt to `Get` a CSR with the same name
- Refactor the rest of Reconcile function to work with `*ServingRuntimeSpec` (which exists in both CR and CSR) rather than SR directly
- Where list of runtimes is retrieved, instead create merged list of SR and CSR with SRs taking precedence

We should have the CSR parts conditional on some flag so that things will work the same as they do now if that CRD does not exist (or controller does not have permisison to list/read them). We may also want to expose and option to explicitly enable/disable use of CSRs in namespace-scope case.

**Comment by chinhuang007** [comment]
I have shared the discussions, design, and implement [here](https://docs.google.com/document/d/1lSqwqmiOeS7rJTtxfSdvxuTK_GzaOwTV5BXfnw2IEJs/edit?usp=sharing). It is a bit more elaborated than what @njhill summarized above. Feel free to make comments!

**Comment by njhill** [comment]
Required changes to the controller have now been completed in #241. Remaining tasks:
- [ ] Update config/install scripts to install CSR CRD and built-in runtimes as CSRs for cluster-scope mode
- [ ] Ensure FVT coverage of both SRs and CSRs

**Comment by rafvasq** [comment]
Closed by https://github.com/kserve/modelmesh-serving/pull/241.

Install and FVT coverage introduced in https://github.com/kserve/modelmesh-serving/pull/252 and improved in https://github.com/kserve/modelmesh-serving/pull/448.
